
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Bell, Calendar, CheckCircle, Clock, AlertCircle, X, Sparkles, TrendingUp, Zap, Settings, Brain, Target } from 'lucide-react';
import CosmicBackground from '../components/CosmicBackground';
import Navigation from '../components/Navigation';
import BottomNavigation from '../components/BottomNavigation';
import AmbientSoundManager from '../components/AmbientSoundManager';
import CursorTrail from '../components/CursorTrail';
import ReminderSettings from '../components/ReminderSettings';
import AutoReminderSettings from '../components/AutoReminderSettings';
import SmartReminderCard from '../components/SmartReminderCard';
import SmartReminderEngine from '../components/SmartReminderEngine';
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { base44 } from '@/api/base44Client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { differenceInDays } from 'date-fns';

export default function Reminders() {
  const [dismissedReminders, setDismissedReminders] = useState(new Set());
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [selectedContact, setSelectedContact] = useState(null); // Retained for ReminderSettings
  const [autoSettingsOpen, setAutoSettingsOpen] = useState(false);
  const queryClient = useQueryClient();

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
    initialData: null
  });

  const theme = user?.theme || 'cosmic';
  const isRetro = theme === 'retro';

  const { data: contacts, isLoading: contactsLoading } = useQuery({
    queryKey: ['contacts'],
    queryFn: () => base44.entities.Contact.list(),
    initialData: []
  });

  const updateContactMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Contact.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contacts'] });
    }
  });

  const handleUpdateContact = async (contactId, data) => {
    await updateContactMutation.mutateAsync({ id: contactId, data });
  };

  // AI-powered reminders (Smart Reminders)
  const aiPoweredReminders = contacts
    .filter(c => 
      c.ai_reminder_data?.should_remind && 
      !dismissedReminders.has(c.id) &&
      (!c.snooze_until || new Date(c.snooze_until) <= new Date())
    )
    .sort((a, b) => {
      const urgencyOrder = { critical: 0, high: 1, medium: 2, low: 3 }; // Adjusted for ascending priority (critical first)
      const aPriority = a.ai_reminder_data.priority || a.ai_reminder_data.urgency || 'medium';
      const bPriority = b.ai_reminder_data.priority || b.ai_reminder_data.urgency || 'medium';
      
      const urgencyDiff = urgencyOrder[aPriority] - urgencyOrder[bPriority];
      if (urgencyDiff !== 0) return urgencyDiff;
      // If priorities are same, sort by confidence (higher confidence first)
      return (b.ai_reminder_data.confidence || 0) - (a.ai_reminder_data.confidence || 0);
    });

  // Traditional time-based reminders
  const upcomingReminders = contacts
    .filter(c => 
      c.reminder_date && 
      !dismissedReminders.has(c.id) &&
      (!c.snooze_until || new Date(c.snooze_until) <= new Date()) &&
      !(c.ai_reminder_data && c.ai_reminder_data.should_remind) // Don't show in both sections
    )
    .sort((a, b) => new Date(a.reminder_date) - new Date(b.reminder_date));

  const handleDismissReminder = (contactId) => {
    setDismissedReminders(prev => new Set(prev).add(contactId));
  };
  
  const handleSaveContactSettings = (contactId, settings) => {
    updateContactMutation.mutate({
      id: contactId,
      data: settings
    });
    setSettingsOpen(false);
    setSelectedContact(null);
  };

  const totalReminders = aiPoweredReminders.length + upcomingReminders.length;
  const criticalReminders = aiPoweredReminders.filter(c => (c.ai_reminder_data.priority || c.ai_reminder_data.urgency) === 'critical').length;
  const highPriorityReminders = aiPoweredReminders.filter(c => (c.ai_reminder_data.priority || c.ai_reminder_data.urgency) === 'high').length;
  const autoGeneratedCount = aiPoweredReminders.filter(c => c.ai_reminder_data.auto_generated).length;

  return (
    <div className="relative w-full min-h-screen overflow-y-auto pb-32">
      <AmbientSoundManager />
      <CursorTrail />
      
      <CosmicBackground theme={theme} />

      <Navigation currentPage="Reminders" theme={theme} />

      <div className="relative z-10 max-w-6xl mx-auto p-6 pt-24">
        {/* Header */}
        <div className="mb-8 text-center">
          <motion.h1
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className={`text-4xl md:text-5xl font-bold mb-2 ${
              isRetro ? 'text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-pink-400 to-purple-500' : 'text-white'
            }`}
            style={{ textShadow: isRetro ? 'none' : '0 0 20px rgba(255, 255, 255, 0.5)' }}
          >
            🔔 Smart Reminders
          </motion.h1>
          <p className={`text-lg ${isRetro ? 'text-pink-300/80' : 'text-white/60'}`}>
            AI-powered insights & follow-up suggestions
          </p>
        </div>

        {/* Stats Row */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-8">
          <StatCard
            label="Total"
            value={totalReminders}
            icon={Bell}
            color={isRetro ? '#00ffff' : '#8b5cf6'}
            theme={theme}
          />
          <StatCard
            label="Critical"
            value={criticalReminders}
            icon={AlertCircle}
            color="#ef4444"
            theme={theme}
          />
          <StatCard
            label="High Priority"
            value={highPriorityReminders}
            icon={TrendingUp}
            color="#f59e0b"
            theme={theme}
          />
          <StatCard
            label="AI-Powered"
            value={aiPoweredReminders.length}
            icon={Brain}
            color={isRetro ? '#ff00ff' : '#ec4899'}
            theme={theme}
          />
          <StatCard
            label="Auto-Generated"
            value={autoGeneratedCount}
            icon={Zap}
            color={isRetro ? '#9d00ff' : '#a78bfa'}
            theme={theme}
          />
        </div>

        {/* AI Reminder Settings Button */}
        <div className="flex justify-end mb-6">
          <Button
            onClick={() => setAutoSettingsOpen(true)}
            className={`flex items-center gap-2 ${
              isRetro
                ? 'bg-gradient-to-r from-cyan-600 to-pink-600 hover:from-cyan-700 hover:to-pink-700'
                : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700'
            }`}
          >
            <Settings className="w-4 h-4" />
            Configure Smart Reminders
          </Button>
        </div>

        {/* AI-Powered Smart Reminders Section */}
        {aiPoweredReminders.length > 0 && (
          <div className="mb-12">
            <div className="flex items-center gap-3 mb-4">
              <Brain className={`w-6 h-6 ${isRetro ? 'text-cyan-400' : 'text-purple-400'}`} />
              <h2 className="text-2xl font-bold text-white">Smart Follow-Up Suggestions</h2>
              <Badge className={`${isRetro ? 'bg-cyan-500/20 text-cyan-300' : 'bg-purple-500/20 text-purple-300'}`}>
                {aiPoweredReminders.length} AI-powered
              </Badge>
            </div>

            <div className="grid gap-4">
              <AnimatePresence>
                {aiPoweredReminders.map((contact) => (
                  <SmartReminderCard
                    key={contact.id}
                    contact={contact}
                    onUpdate={(data) => handleUpdateContact(contact.id, data)}
                    onDismiss={() => handleDismissReminder(contact.id)}
                    onOpenSettings={() => {
                      setSelectedContact(contact);
                      setSettingsOpen(true);
                    }}
                    theme={theme}
                  />
                ))}
              </AnimatePresence>
            </div>
          </div>
        )}

        {/* Traditional Time-Based Reminders Section */}
        {upcomingReminders.length > 0 && (
          <div>
            <div className="flex items-center gap-3 mb-4">
              <Calendar className={`w-6 h-6 ${isRetro ? 'text-pink-400' : 'text-pink-400'}`} />
              <h2 className="text-2xl font-bold text-white">Scheduled Reminders</h2>
              <Badge className="bg-pink-500/20 text-pink-300">
                {upcomingReminders.length} upcoming
              </Badge>
            </div>

            <div className="grid gap-4">
              <AnimatePresence>
                {upcomingReminders.map((contact) => {
                  const reminderDate = new Date(contact.reminder_date);
                  const today = new Date();
                  today.setHours(0,0,0,0); // Normalize today to start of day for accurate comparison

                  const daysDiff = differenceInDays(reminderDate, today);
                  const isPast = daysDiff < 0;
                  const isToday = daysDiff === 0;
                  const isSoon = daysDiff <= 3 && daysDiff > 0;

                  return (
                    <motion.div
                      key={contact.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, x: -20 }}
                      className={`p-6 rounded-2xl border backdrop-blur-xl transition-all ${
                        isRetro
                          ? isPast ? 'bg-red-900/40 border-red-400/50' :
                            isToday ? 'bg-pink-900/40 border-pink-400/50' :
                            isSoon ? 'bg-yellow-900/40 border-yellow-400/50' :
                            'bg-black/60 border-cyan-400/30'
                          : isPast ? 'bg-red-950/40 border-red-400/30' :
                            isToday ? 'bg-pink-950/40 border-pink-400/30' :
                            isSoon ? 'bg-yellow-950/40 border-yellow-400/30' :
                            'bg-white/5 border-white/10'
                      }`}
                    >
                      <div className="flex items-start justify-between mb-4">
                        <div className="flex items-center gap-3">
                          {contact.avatar_url ? (
                            <img src={contact.avatar_url} alt={contact.name} className="w-12 h-12 rounded-full object-cover border-2 border-white/20" />
                          ) : (
                            <div className="w-12 h-12 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center border-2 border-white/20">
                              <span className="text-xl font-bold text-white">{contact.name[0]?.toUpperCase()}</span>
                            </div>
                          )}
                          <div>
                            <h3 className="text-lg font-semibold text-white">{contact.name}</h3>
                            <p className="text-white/60 text-sm capitalize">{contact.relationship?.replace('_', ' ')}</p>
                          </div>
                        </div>

                        <button
                          onClick={() => handleDismissReminder(contact.id)}
                          className="p-2 rounded-full hover:bg-white/10 transition-colors"
                        >
                          <X className="w-5 h-5 text-white/60 hover:text-white" />
                        </button>
                      </div>

                      <div className="flex items-center gap-2 mb-4">
                        <Clock className={`w-5 h-5 ${isPast ? 'text-red-400' : isToday ? 'text-pink-400' : isSoon ? 'text-yellow-400' : 'text-white/60'}`} />
                        <span className={`font-medium ${isPast ? 'text-red-400' : isToday ? 'text-pink-400' : isSoon ? 'text-yellow-400' : 'text-white'}`}>
                          {isPast ? `Overdue (${Math.abs(daysDiff)} days ago)` :
                          isToday ? 'Due Today' :
                          isSoon ? `Due in ${daysDiff} days` :
                          `Due ${reminderDate.toLocaleDateString()}`}
                        </span>
                      </div>

                      <div className="flex gap-2">
                        <Button
                          onClick={() => handleUpdateContact(contact.id, { 
                            reminder_date: null,
                            last_contacted: new Date().toISOString().split('T')[0] // Mark today as last contacted
                          })}
                          className="flex-1 bg-green-600 hover:bg-green-700"
                        >
                          <CheckCircle className="w-4 h-4 mr-2" />
                          Mark Complete
                        </Button>
                        <Button
                          onClick={() => {
                            setSelectedContact(contact);
                            setSettingsOpen(true);
                          }}
                          variant="outline"
                          className="bg-white/5 border-white/10 text-white hover:bg-white/10"
                        >
                          Edit
                        </Button>
                      </div>
                    </motion.div>
                  );
                })}
              </AnimatePresence>
            </div>
          </div>
        )}

        {/* Enhanced Empty State */}
        {totalReminders === 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center py-16 max-w-2xl mx-auto"
          >
            <motion.div
              animate={{
                scale: [1, 1.1, 1],
                rotate: [0, 10, -10, 0]
              }}
              transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}
              className="mb-6"
            >
              <Brain className="w-24 h-24 text-white/20 mx-auto" />
            </motion.div>
            
            <h3 className="text-2xl font-bold text-white mb-3">Your network is in good shape</h3>
            <p className="text-white/60 text-lg mb-6 leading-relaxed">
              No urgent follow-ups detected right now. The AI is monitoring your relationships 
              and will suggest when it's time to reach out to someone.
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className={`p-4 rounded-xl border ${
                  isRetro 
                    ? 'bg-black/40 border-cyan-400/30' 
                    : 'bg-white/5 border-white/10'
                }`}
              >
                <Target className={`w-8 h-8 mx-auto mb-2 ${isRetro ? 'text-cyan-400' : 'text-purple-400'}`} />
                <h4 className="text-white font-semibold text-sm mb-1">AI Analysis</h4>
                <p className="text-white/60 text-xs">Continuously monitors contact patterns</p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className={`p-4 rounded-xl border ${
                  isRetro 
                    ? 'bg-black/40 border-pink-400/30' 
                    : 'bg-white/5 border-white/10'
                }`}
              >
                <Sparkles className={`w-8 h-8 mx-auto mb-2 ${isRetro ? 'text-pink-400' : 'text-pink-400'}`} />
                <h4 className="text-white font-semibold text-sm mb-1">Smart Suggestions</h4>
                <p className="text-white/60 text-xs">Get notified when someone needs attention</p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className={`p-4 rounded-xl border ${
                  isRetro 
                    ? 'bg-black/40 border-purple-400/30' 
                    : 'bg-white/5 border-white/10'
                }`}
              >
                <TrendingUp className={`w-8 h-8 mx-auto mb-2 ${isRetro ? 'text-purple-400' : 'text-blue-400'}`} />
                <h4 className="text-white font-semibold text-sm mb-1">Stay Connected</h4>
                <p className="text-white/60 text-xs">Never let important relationships drift</p>
              </motion.div>
            </div>

            <Button
              onClick={() => setAutoSettingsOpen(true)}
              className={`${
                isRetro
                  ? 'bg-gradient-to-r from-cyan-600 to-pink-600 hover:from-cyan-700 hover:to-pink-700'
                  : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700'
              }`}
            >
              <Settings className="w-4 h-4 mr-2" />
              Configure Smart Reminders
            </Button>
          </motion.div>
        )}
      </div>

      <AnimatePresence>
        {settingsOpen && selectedContact && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50"
              onClick={() => {
                setSettingsOpen(false);
                setSelectedContact(null);
              }}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              transition={{ type: 'spring', damping: 25, stiffness: 300 }}
              className="fixed inset-0 z-50 flex items-center justify-center p-4 pointer-events-none"
            >
              <div className="max-w-2xl w-full pointer-events-auto">
                <ReminderSettings
                  contact={selectedContact}
                  onSave={(settings) => handleSaveContactSettings(selectedContact.id, settings)}
                  onClose={() => {
                    setSettingsOpen(false);
                    setSelectedContact(null);
                  }}
                  theme={theme}
                />
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      <AutoReminderSettings
        isOpen={autoSettingsOpen}
        onClose={() => setAutoSettingsOpen(false)}
        theme={theme}
      />

      <SmartReminderEngine
        enabled={user?.auto_reminders_enabled ?? true}
        autoSetReminders={user?.auto_set_reminders ?? true}
        checkInterval={user?.check_frequency || '6h'}
        debugMode={false}
      />

      <BottomNavigation currentPage="Reminders" />
    </div>
  );
}

function StatCard({ label, value, icon: Icon, color, theme }) {
  const isRetro = theme === 'retro';
  
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      whileHover={{ scale: 1.05 }}
      className={`p-4 rounded-xl border backdrop-blur-xl ${
        isRetro 
          ? 'bg-black/60 border-cyan-400/30' 
          : 'bg-white/5 border-white/10'
      }`}
    >
      <Icon className="w-6 h-6 mb-2" style={{ color }} />
      <div className="text-3xl font-bold text-white mb-1">{value}</div>
      <div className="text-white/60 text-sm">{label}</div>
    </motion.div>
  );
}
